# Generated by Django 4.2 on 2025-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menudown",
            options={
                "verbose_name": "Нижнее меню",
                "verbose_name_plural": "Нижние меню",
            },
        ),
        migrations.AlterModelOptions(
            name="menutop",
            options={
                "verbose_name": "Верхнее меню",
                "verbose_name_plural": "Верхнее меню",
            },
        ),
        migrations.AddField(
            model_name="menudown",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="menutop",
            name="link",
            field=models.CharField(max_length=200, null=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="menudown",
            name="link",
            field=models.CharField(max_length=200, null=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="menutop",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
    ]
