# Generated by Django 4.2 on 2025-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_menudown_options_alter_menutop_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="link",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.ImageField(
                null=True, upload_to="photos/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="footertext",
            name="text",
            field=models.TextField(null=True, verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(
                null=True, upload_to="photos/", verbose_name="Логотип"
            ),
        ),
        migrations.AlterField(
            model_name="menudown",
            name="link",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="menudown",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="menutop",
            name="link",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
    ]
