# Generated by Django 4.2 on 2025-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_logo_link_alter_carousel_image_alter_carousel_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menutop",
            name="link",
        ),
        migrations.AddField(
            model_name="menutop",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
