# Generated by Django 4.2 on 2025-05-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_remove_menutop_link_menutop_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menutop",
            name="slug",
        ),
        migrations.AddField(
            model_name="menutop",
            name="link",
            field=models.SlugField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
    ]
