# Generated by Django 4.2 on 2025-05-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_remove_menutop_slug_menutop_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="link",
            field=models.URLField(null=True, unique=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="menudown",
            name="link",
            field=models.URLField(null=True, unique=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="menutop",
            name="link",
            field=models.URLField(null=True, unique=True, verbose_name="Ссылка"),
        ),
    ]
