# Generated by Django 4.2 on 2025-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_alter_logo_link_alter_menudown_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="link",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="menudown",
            name="link",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="menutop",
            name="link",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Ссылка"
            ),
        ),
    ]
