# Generated by Django 4.2 on 2025-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_remove_menudown_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="title",
            field=models.CharField(max_length=200, null=True, verbose_name="Заголовок"),
        ),
    ]
