# Generated by Django 4.2 on 2025-05-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Carousel",
        ),
    ]
