# Generated by Django 4.2 on 2025-03-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_typeproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
