# Generated by Django 4.2 on 2025-05-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_basket_delete_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set(),
        ),
    ]
